version: "3"
services:
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_bikes
  app:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db

